lib/src/graph.dart
=> Add reset cache to graphql queries

lib/src/api.dart
new api:
* sync contacts
* ack sync contacts
=> phone numbers reverse indexing

lib/src/graph.dart, pubspec.yaml
=> timestamp field added

lib/src/api.dart, pubspec.yaml
=> Adding update firebase token call

lib/src/api.dart, pubspec.yaml
=> added backup call

lib/src/api.dart, pubspec.yaml
=> get funder job

lib/src/graph.dart, pubspec.yaml
=> added get community businesses from the graph

lib/src/api.dart, lib/src/graph.dart, lib/src/queries.dart, lib/src/web3.dart, pubspec.yaml
=> upgrade graph & create wallet 2

lib/src/api.dart, pubspec.yaml
=> added networks to getWallet endpoint

lib/src/graph.dart, lib/src/queries.dart, pubspec.yaml
=> graph - new client & getAccountTokens query

lib/src/graph.dart, lib/src/queries.dart, pubspec.yaml
=> Get all tokens from graph

lib/src/graph.dart, lib/src/queries.dart, pubspec.yaml
=> get token & get tokens queries

lib/src/api.dart, lib/src/web3.dart, pubspec.yaml
=> Dai points transfer added

lib/src/api.dart, pubspec.yaml
=> added multi endpoint

lib/src/api.dart, pubspec.yaml
=> fixed endpoint

lib/src/api.dart, pubspec.yaml
=> Make backup optional

lib/src/explorer_api.dart, lib/wallet_core.dart, pubspec.yaml
=> changed token_api to explorer api

lib/src/api.dart, lib/src/web3.dart
=> pass reserve & marketMaker ContractAddresses

example/cash.token.dart, example/onboarding.dart, lib/src/api.dart, lib/src/explorer_api.dart, lib/src/graph.dart, lib/src/market_api.dart, lib/src/queries.dart, lib/src/web3.dart
=> added new bridge subgraph & transfers using AMB

lib/src/web3.dart
=> Retrieve Multiple Private Keys from mnemonic

lib/src/wallet_api.dart, lib/src/web3.dart
=> amount can be either num / BigInt

lib/src/wallet_api.dart
=> wallet version

lib/src/wallet_api.dart, lib/src/web3.dart
=> allow nft transfer

lib/src/wallet_api.dart
=> add isBlacklisted

lib/src/graph.dart
=> disable NFT graph cache

lib/models/api.dart, lib/src/api.dart, lib/src/wallet_api.dart, lib/src/web3.dart
=> minor fixes

lib/src/studio_api.dart, lib/src/wallet_api.dart, pubspec.yaml
=> interceptors

CHANGELOG.md, pubspec.yaml
=> downgrade path
